---
- hosts: all
  become: yes

  handlers:
    - name: restart apache2
      systemd:
        name: apache2
        state: restarted
    - name: restart mongodb
      systemd:
        name: mongodb
        state: restarted
    - name: install swimwithjj emailer service
      systemd:
        name: swimwithjj-emailer
        state: started
        daemon_reload: yes
    - name: restart swimwithjj emailer service
      systemd:
        name: swimwithjj-emailer
        state: restarted

  tasks:
    # Install apt dependencies
    - name: install dependencies
      apt: name={{ item }}
      with_items:
        - python
        - apache2
        - apache2-utils
        - mongodb
        - python-pip
        - python-yaml
        - python-passlib
      notify:
        - restart apache2
        - restart mongodb

    - name: install python dependencies
      pip: name={{ item }}
      with_items:
        - pymongo
        - pystache
        - stripe

    # Enable apache mods
    - name: enable apache mods
      apache2_module: state=present name={{ item }}
      with_items:
        - cgid
        - deflate
        - headers
        - expires
        - filter
        - ssl
      notify:
        - restart apache2

    # Setup SSL
    - name: make sure apache is started
      systemd:
        name: apache2
        state: started
    - name: copy ssl setup script
      copy:
        src: bin/setup-ssl.sh
        dest: /tmp
        mode: 0664
    - name: run ssl setup script
      command: /tmp/setup-ssl.sh
      args:
        creates: /etc/letsencrypt/live/example.com/cert.pem
      notify:
        - restart apache2

    # Setup settings dir
    - name: setup settings dir
      file: path=/etc/swimwithjj state=directory mode=0755 owner=root group=root

    # Copy webapp
    - name: ensure webapp root exists
      tags: webapp
      file: path=/var/www/www.swimwithjj.com state=directory mode=0755 owner={{ansible_ssh_user}} group=www-data
    - name: copy webapp
      tags: webapp
      become: no
      synchronize:
        src: webapp/
        dest: /var/www/www.swimwithjj.com
        delete: yes
    - name: set cgi permissions
      tags: webapp
      file: path={{ item }} mode='a+x'
      with_items:
        - /var/www/www.swimwithjj.com/form-handler.cgi
        - /var/www/www.swimwithjj.com/config.cgi
        - /var/www/www.swimwithjj.com/session-cal.cgi
        - /var/www/www.swimwithjj.com/admin/admin-handler.cgi
    - name: copy webapp settings
      tags: webapp
      copy: src={{ webapp_settings_path }} dest=/etc/swimwithjj/webapp.yaml owner=root group=root

    # Copy apache and vhost configs
    - name: copy apache2 default conf
      copy: src=conf/apache.conf dest=/etc/apache2/conf-available/httpd.conf
      notify:
        - restart apache2
    - name: enable apache2 default conf
      command: a2enconf httpd
      args:
        creates: /etc/apache2/conf-enabled/httpd.conf
      notify:
        - restart apache2
    - name: copy webapp vhost conf
      copy: src=conf/apache-vhost.conf dest=/etc/apache2/sites-available/www.swimwithjj.com.conf
      notify:
        - restart apache2

    # Enable site
    - name: enable site
      command: a2ensite www.swimwithjj.com.conf
      args:
        creates: /etc/apache2/sites-enabled/www.swimwithjj.com.conf
      notify:
        - restart apache2

    # Add admin http password
    - name: add admin http password
      htpasswd: path=/etc/apache2/htpasswd name=admin password={{ admin_password }} owner=root group=www-data mode=0640

    # Install Emailer Service
    - name: copy python code
      tags: emailer
      copy: src=lib/emailer.py dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
      notify:
        - restart swimwithjj emailer service

    - name: copy server settings
      tags: emailer
      copy: src={{ server_settings_path }} dest=/etc/swimwithjj/server.yaml owner=root group=root
      notify:
        - restart swimwithjj emailer service

    - name: copy emailer service runner
      tags: emailer
      notify:
        - restart swimwithjj emailer service
      copy: src=bin/swimwithjj-email-service.py dest=/usr/local/bin owner=root group=root mode=0755

    - name: copy systemd service definition
      tags: emailer
      copy: src=conf/swimwithjj-emailer.service dest=/etc/systemd/system owner=root group=root mode=0664
      notify:
        - install swimwithjj emailer service


# vim:ft=ansible:
