---
- hosts: all
  become_user: root
  become: yes

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
    - name: restart mongodb
      service: name=mongodb state=restarted
    - name: restart swimwithjj email service
      service: name=swimwithjj-email-service state=restarted

  tasks:
    # Install apt dependencies
    - name: install dependencies
      apt: name={{ item }}
      with_items:
        - python
        - apache2
        - apache2-utils
        - mongodb
        - python-pip
        - python-yaml
      notify:
        - restart apache2
        - restart mongodb

    - name: install python dependencies
      pip: name={{ item }}
      with_items:
        - pymongo
        - pystache
        - stripe

    # Enable apache mods
    - name: enable apache mods
      apache2_module: state=present name={{ item }}
      with_items:
        - cgid
        - deflate
        - headers
        - expires
        - filter
      notify:
        - restart apache2

    # Copy webapp
    - name: copy webapp
      synchronize: src=webapp/ dest=/var/www/www.swimwithjj.com
    - name: set cgi permissions
      file: path={{ item }} mode='a+x'
      with_items:
        - /var/www/www.swimwithjj.com/form-handler.cgi
        - /var/www/www.swimwithjj.com/session-cal.cgi
        - /var/www/www.swimwithjj.com/admin/admin-handler.cgi

    # Copy apache and vhost configs
    - name: copy apache2 default conf
      copy: src=conf/apache.conf dest=/etc/apache2/conf-available/httpd.conf
      notify:
        - restart apache2
    - name: enable apache2 default conf
      command: a2enconf httpd
      args:
        creates: /etc/apache2/conf-enabled/httpd.conf
      notify:
        - restart apache2
    - name: copy webapp vhost conf
      copy: src=conf/apache-vhost.conf dest=/etc/apache2/sites-available/www.swimwithjj.com.conf
      notify:
        - restart apache2

    # Enable site
    - name: enable site
      command: a2ensite www.swimwithjj.com.conf
      args:
        creates: /etc/apache2/sites-enabled/www.swimwithjj.com.conf
      notify:
        - restart apache2

    # Install Email Service
    - name: copy python code
      copy: src=lib/emailer.py dest=/usr/local/lib/python2.7/dist-packages owner=root group=root
      notify:
        - restart swimwithjj email service

    - name: setup settings dir
      file: path=/etc/swimwithjj state=directory mode=0755 owner=root group=root

    - name: copy settings.yaml
      copy: src=conf/{{ settings_file }} dest=/etc/swimwithjj/settings.yaml  owner=root group=root
      notify:
        - restart swimwithjj email service

    - name: copy email service runner
      notify:
        - restart swimwithjj email service
      copy: src=bin/swimwithjj-email-service.py dest=/usr/local/bin owner=root group=root mode=0755

    - name: copy upstart service definition
      copy: src=conf/upstart.conf dest=/etc/init/swimwithjj-email-service.conf owner=root group=root
      notify:
        - restart swimwithjj email service


# vim:ft=ansible:
